import numpy as np

CompaniesNamesStock = {
        # Industrial
        "SPIN.CA": "Alexandria Spinning & Weaving",
        "ALUM.CA": "Arab Aluminum",
        "ACGC.CA": "Arab Cotton Ginning",
        "APSW.CA": "Unirab Polvara Spinning",
        "ARVA.CA": "Arab Valves Company",
        "ASCM.CA": "ASCOM Minging",
        "BIDI.CA": "BID - El Badr for Investment & Development",
        "PRCL.CA": "General Ceramics & Porcelain",
        "DTPP.CA": "Delta Printing & Packaging",
        "DSCW.CA": "Dice Ready-Made Garments",
        "EGAL.CA": "Egypt Aluminum",
        "IRON.CA": "Egyptian Iron & Steel",
        "EPPK.CA": "El Ahram Printing & Packaging",
        "EEII.CA": "Arab Engineering Industries",
        "IRAX.CA": "El Ezz Aldekhela Steel Alexandria",
        "ECAP.CA": "Al Ezz Ceramics & Porcelain",
        "KABO.CA": "El-Nasr Clothing (KABO)",
        "SMPP.CA": "El Shorouk Modern Printing & Packaging",
        "ELEC.CA": "Electro Cable Egypt",
        "SWDY.CA": "Elsewedy Electric",
        "ENGC.CA": "Industrial Engineering Co.",
        "FCMD.CA": "Future Care For Medical Industries",
        "GDWA.CA": "Gadwa Industrial Development",
        "GTWL.CA": "Golden Textiles",
        "GTEX.CA": "GTEX Commercial & Industrial",
        "DIFC.CA": "International Dry Ice Co. (DIFCO)",
        "ISMQ.CA": "Iron & Steel Mines & Quarries",
        "LCSW.CA": "Lecico Egypt",
        "MBEG.CA": "MB Engineering",
        "MEGM.CA": "Middle East Glass",
        "NAPR.CA": "National Printing Company",
        "ORAS.CA": "Orascom Construction",
        "ORWE.CA": "Oriental Weavers",
        "PACH.CA": "Pachin S.A.E.",
        "RAKT.CA": "Rakta Paper Manufacturing",
        "RKAZ.CA": "Rekaz Holding",
        "RUBX.CA": "Rubex International",
        "SIMO.CA": "Simo Plastic Industries",
        "SLAR.CA": "Solar Soul",
        "UNIP.CA": "Universal Paper & Packaging",
        "VERT.CA": "Vertica Co.",
        
        # Real Estate
        "AMER.CA": "Amer Group Holding",
        "ARAB.CA": "Arab Developers Holding",
        "ADRI.CA": "Arab for Real Estate Development & Investment",
        "RREI.CA": "Arab Real Estate Investment",
        "AIFI.CA": "Atlas for Investment & Food Industries",
        "CIRA.CA": "CIRA Education",
        "COPR.CA": "Copper Commercial Investment",
        "CRST.CA": "Creast Mark Contracting",
        "DCRC.CA": "Delta for Construction & Rebuilding",
        "AREH.CA": "Real Estate Egyptian Consortium",
        "EHDR.CA": "Egyptians for Housing",
        "AFDI.CA": "Al Ahly Development & Investment",
        "ELKA.CA": "Cairo Housing & Development",
        "OBRI.CA": "El-Ebour Real Estate",
        "ELSH.CA": "Al Shams Housing",
        "SPHT.CA": "El Shams Pyramids Hotels",
        "UEGC.CA": "El Saeed Contracting",
        "EMFD.CA": "Emaar Misr",
        "FIRE.CA": "First Investment & Real Estate Development",
        "GIHD.CA": "Gharbia Islamic Housing",
        "GPPL.CA": "Golden Pyramids Plaza",
        "CCRS.CA": "Gulf Canadian Real Estate",
        "HELI.CA": "Heliopolis Housing",
        "IDRE.CA": "Ismailia Development",
        "MASR.CA": "Madinet Masr",
        "MENA.CA": "Mena Touristic & Real Estate",
        "NARE.CA": "Naeem Real Estate",
        "NHPS.CA": "National Housing Professional Syndicates",
        "ORHD.CA": "Orascom Development Egypt",
        "PHDC.CA": "Palm Hills Development",
        "PRDC.CA": "Pioneers Properties",
        "OCDI.CA": "SODIC",
        "TMGH.CA": "Talaat Moustafa Group",
        "TANM.CA": "Tanmiya Real Estate",
        "UNIT.CA": "United Housing & Development",
        "UTOP.CA": "Utopia Real Estate Investment & Tourism",
        "ZMID.CA": "Zahraa El Maadi",
        
        # Banking
        "ADIB.CA": "Abu Dhabi Islamic Bank Egypt",
        "SAUD.CA": "Al Baraka Bank Egypt",
        "BQDC.CA": "Banque du Caire",
        "COMI.CA": "Commercial International Bank",
        "CIEB.CA": "Credit Agricole Egypt",
        "EGBE.CA": "Egyptian Gulf Bank",
        "EXPA.CA": "Export Development Bank",
        "FAIT.CA": "Faisal Islamic Bank",
        "HDBK.CA": "Housing & Development Bank",
        "NBKE.CA": "National Bank of Kuwait Egypt",
        "QNBE.CA": "QNB Alahli",
        "SAIB.CA": "SAIB Bank",
        "CANA.CA": "Suez Canal Bank",
        "UBEE.CA": "The United Bank",
        
        # FinTech
        "EFIH.CA": "e-Finance",
        "FWRY.CA": "Fawry",
        "VALU.CA": "ValU Consumer Finance",
        
        # Telecom
        "ETEL.CA": "Telecom Egypt",
        
        # Automotive
        "GBCO.CA": "GB Corp",
        
        # ETF
        "EGX30ETF.CA": "EGX30 ETF",
}

CompanySectorsStock = {
        # Industrial
        "SPIN.CA": "Industrials",
        "ALUM.CA": "Industrials",
        "ACGC.CA": "Industrials",
        "APSW.CA": "Industrials",
        "ARVA.CA": "Industrials",
        "ASCM.CA": "Industrials",
        "BIDI.CA": "Industrials",
        "PRCL.CA": "Industrials",
        "DTPP.CA": "Industrials",
        "DSCW.CA": "Industrials",
        "EGAL.CA": "Industrials",
        "IRON.CA": "Industrials",
        "EPPK.CA": "Industrials",
        "EEII.CA": "Industrials",
        "IRAX.CA": "Industrials",
        "ECAP.CA": "Industrials",
        "KABO.CA": "Industrials",
        "SMPP.CA": "Industrials",
        "ELEC.CA": "Industrials",
        "SWDY.CA": "Industrials",
        "ENGC.CA": "Industrials",
        "FCMD.CA": "Industrials",
        "GDWA.CA": "Industrials",
        "GTWL.CA": "Industrials",
        "GTEX.CA": "Industrials",
        "DIFC.CA": "Industrials",
        "ISMQ.CA": "Industrials",
        "LCSW.CA": "Industrials",
        "MBEG.CA": "Industrials",
        "MEGM.CA": "Industrials",
        "NAPR.CA": "Industrials",
        "ORAS.CA": "Industrials",
        "ORWE.CA": "Industrials",
        "PACH.CA": "Industrials",
        "RAKT.CA": "Industrials",
        "RKAZ.CA": "Industrials",
        "RUBX.CA": "Industrials",
        "SIMO.CA": "Industrials",
        "SLAR.CA": "Industrials",
        "UNIP.CA": "Industrials",
        "VERT.CA": "Industrials",

        # Real Estate
        "AMER.CA": "Real Estate",
        "ARAB.CA": "Real Estate",
        "ADRI.CA": "Real Estate",
        "RREI.CA": "Real Estate",
        "AIFI.CA": "Real Estate",
        "CIRA.CA": "Real Estate",
        "COPR.CA": "Real Estate",
        "CRST.CA": "Real Estate",
        "DCRC.CA": "Real Estate",
        "AREH.CA": "Real Estate",
        "EHDR.CA": "Real Estate",
        "AFDI.CA": "Real Estate",
        "ELKA.CA": "Real Estate",
        "OBRI.CA": "Real Estate",
        "ELSH.CA": "Real Estate",
        "SPHT.CA": "Real Estate",
        "UEGC.CA": "Real Estate",
        "EMFD.CA": "Real Estate",
        "FIRE.CA": "Real Estate",
        "GIHD.CA": "Real Estate",
        "GPPL.CA": "Real Estate",
        "CCRS.CA": "Real Estate",
        "HELI.CA": "Real Estate",
        "IDRE.CA": "Real Estate",
        "MASR.CA": "Real Estate",
        "MENA.CA": "Real Estate",
        "NARE.CA": "Real Estate",
        "NHPS.CA": "Real Estate",
        "ORHD.CA": "Real Estate",
        "PHDC.CA": "Real Estate",
        "PRDC.CA": "Real Estate",
        "OCDI.CA": "Real Estate",
        "TMGH.CA": "Real Estate",
        "TANM.CA": "Real Estate",
        "UNIT.CA": "Real Estate",
        "UTOP.CA": "Real Estate",
        "ZMID.CA": "Real Estate",

        # Banking
        "ADIB.CA": "Banking",
        "SAUD.CA": "Banking",
        "BQDC.CA": "Banking",
        "COMI.CA": "Banking",
        "CIEB.CA": "Banking",
        "EGBE.CA": "Banking",
        "EXPA.CA": "Banking",
        "FAIT.CA": "Banking",
        "HDBK.CA": "Banking",
        "NBKE.CA": "Banking",
        "QNBE.CA": "Banking",
        "SAIB.CA": "Banking",
        "CANA.CA": "Banking",
        "UBEE.CA": "Banking",

        # FinTech
        "EFIH.CA": "FinTech",
        "FWRY.CA": "FinTech",
        "VALU.CA": "FinTech",

        # Telecom
        "ETEL.CA": "Telecom",

        # Automotive
        "GBCO.CA": "Automotive",

        # ETF
        "EGX30ETF.CA": "ETF",
}

MANUAL_SECTOR_MAP = dict(CompanySectorsStock)

SECTORS = [
    "Financials",
    "Basic Materials",
    "Industrials",
    "Consumer Goods",
    "Consumer Services",
    "Technology",
    "Health Care",
    "Utilities",
    "Telecom",
    "Oil & Gas",
    "Real Estate",
    "Banking",
    "FinTech",
    "Automotive",
    "ETF",
]


NAME_MAP = {
    "Abu Kir Fertilizers": "Abu Qir Fertilizers",
    "Alexandria Container & Cargo Handling": "Alexandria Containers And Goods",
    "Alexandria Mineral Oils": "Alexandria Mineral Oils Company",
    "Cairo Poultry (Koki)": "Cairo Poultry",
    "Commercial International Bank (CIB)": "Commercial International Bank (Egypt)",
    "CIB Egypt": "Commercial International Bank (Egypt)",
    "Egyptian Electrical Cables": "Electro Cable Egypt Company",
    "El Sewedy Electric": "El Sewedy Electric Company",
    "Fawry": "Fawry for Banking Technology and Electronic Payment",
    "Misr Capital": "Misr Financial Investments",
    "Orascom Construction": "Orascom Construction Industries",
    "Orascom Telecom Media & Technology": "Global Telecom Holding",
    "Palm Hills Developments": "Palm Hills Development Company",
    "Raya Holding": "Raya Holding for Financial Investments",
    "Talaat Moustafa Group": "TMG Holding",
}


FALLBACK_METADATA = {
    "Unit Investments": {
        "Sector": "Financials",
        "Price": np.nan,
        "YTD": np.nan,
        "M.Cap": np.nan,
    },
    "Hassan Allam Holding": {
        "Sector": "Industrials",
        "Price": np.nan,
        "YTD": np.nan,
        "M.Cap": np.nan,
    },
    "Modern Furniture": {
        "Sector": "Consumer Goods",
        "Price": np.nan,
        "YTD": np.nan,
        "M.Cap": np.nan,
    },
}


TRADING_DAYS = 252
SHORT_WINDOW = 21
LONG_WINDOW = 63
VOL_WINDOW = 30
